name: vault
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    environment:
      VAULT_ADDR: "https://localhost:8200"
      VAULT_API_ADDR: "https://localhost:8200"
      VAULT_ADDRESS: "https://localhost:8200"
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/data"
            }
          },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          }],
          "default_lease_ttl": "1h",
          "max_lease_ttl": "24h",
          "ui": true
        }
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./data:/vault/data/:rw
    cap_add:
      - IPC_LOCK
    command: ["server"]
